const cloudinary = require('cloudinary').v2;
const Problem = require("../models/problem");
const User = require("../models/user");
const SolutionVideo = require("../models/solutionVideo");
const { sanitizeFilter } = require('mongoose');


cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET
});

const generateUploadSignature = async (req, res) => {
  try {
    const { problemId } = req.params;
    
    const userId = req.result._id;
    // Verify problem exists
    const problem = await Problem.findById(problemId);
    if (!problem) {
      return res.status(404).json({ error: 'Problem not found' });
    }

    // Generate unique public_id for the video , ready the signature
    const timestamp = Math.round(new Date().getTime() / 1000);
    const publicId = `leetcode-solutions/${problemId}/${userId}_${timestamp}`; // can be generated by us or cloudanary
    
    // Upload parameters
    const uploadParams = {
      timestamp: timestamp,
      public_id: publicId,
    };

    // Generate signature
    const signature = cloudinary.utils.api_sign_request(
      uploadParams,
      process.env.CLOUDINARY_API_SECRET
    );

    //timeStamp , signature,publicId are imp to send to frontend , as this will be sended to cloudinary
    // cloudianry there verify it as it has its secret key
    res.json({
      signature,
      timestamp,
      public_id: publicId,
      api_key: process.env.CLOUDINARY_API_KEY,
      cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
      upload_url: `https://api.cloudinary.com/v1_1/${process.env.CLOUDINARY_CLOUD_NAME}/video/upload`,
    });

  } catch (error) {
    console.error('Error generating upload signature:', error);
    res.status(500).json({ error: 'Failed to generate upload credentials' });
  }
};

//frontend will upload data ,and send meta data
const saveVideoMetadata = async (req, res) => {
  try {
    const {
      problemId,
      cloudinaryPublicId,
      secureUrl,
      duration,
    } = req.body;

    const userId = req.result._id;

    // Verify the upload with Cloudinary
    //send all the data if it is present
    const cloudinaryResource = await cloudinary.api.resource(
      cloudinaryPublicId,
      { resource_type: 'video' }
    );
    
    if (!cloudinaryResource) {
      return res.status(400).json({ error: 'Video not found on Cloudinary' });
    }

    // Check if video already exists for this problem and user
    const existingVideo = await SolutionVideo.findOne({
      problemId,
      userId,
      cloudinaryPublicId
    });

    if (existingVideo) {
      return res.status(409).json({ error: 'Video already exists' });
    }

    // const thumbnailUrl = cloudinary.url(cloudinaryResource.public_id, {
    // resource_type: 'image',  
    // transformation: [
    // { width: 400, height: 225, crop: 'fill' },
    // { quality: 'auto' },
    // { start_offset: 'auto' }  
    // ],
    // format: 'jpg'
    // });
    const thumbnailUrl = cloudinary.image("cloudinaryResource.public_id",{resource_type:"video"});

    // Create video solution record
    const videoSolution = await SolutionVideo.create({
      problemId,
      userId,
      cloudinaryPublicId,
      secureUrl,
      duration: cloudinaryResource.duration || duration,
      thumbnailUrl
    });




    res.status(201).json({
      message: 'Video solution saved successfully',
      videoSolution: {
        id: videoSolution._id,
        thumbnailUrl: videoSolution.thumbnailUrl,
        duration: videoSolution.duration,
        uploadedAt: videoSolution.createdAt
      }
    });

  } catch (error) {
    console.error('Error saving video metadata:', error);
    res.status(500).json({ error: 'Failed to save video metadata' });
  }
};

const deleteVideo = async (req, res) => {
  try {
    const { problemId } = req.params;
    const userId = req.result._id;

    // First check if video exists
    const video = await SolutionVideo.findOne({ problemId });
    
    if (!video) {
      return res.status(404).json({ 
        error: 'Video Solution Not Found',
        message: `No video solution exists for problem ID: ${problemId}`,
        problemId: problemId
      });
    }

    // Delete from database
    await SolutionVideo.findOneAndDelete({ problemId });
    
    // Delete from Cloudinary
    await cloudinary.uploader.destroy(video.cloudinaryPublicId, { 
      resource_type: 'video', 
      invalidate: true 
    });

    res.json({ 
      success: true,
      message: 'Video solution deleted successfully',
      deletedVideo: {
        problemId: video.problemId,
        videoId: video._id
      }
    });

  } catch (error) {
    console.error('Error deleting video:', error);
    res.status(500).json({ 
      error: 'Failed to delete video solution',
      message: error.message 
    });
  }
};

const getVideoByProblemId = async (req, res) => {
  try {
    const { problemId } = req.params;
    
    const video = await SolutionVideo.findOne({ problemId });
    
    if (!video) {
      return res.status(404).json({ 
        success: false, 
        message: 'No video solution found for this problem' 
      });
    }
    
    res.json({ 
      success: true, 
      videoSolution: video 
    });
  } catch (error) {
    res.status(500).json({ 
      success: false, 
      error: error.message 
    });
  }
};
module.exports = {generateUploadSignature,saveVideoMetadata,deleteVideo,getVideoByProblemId};


